export const TERMS = {
    birimAdi: 'Teftiş Kurulu Müdürlüğü',
    birimKisa: 'Teftiş Kurulu',
    mufettis: 'Müfettiş',
    gozetimSorumlusu: 'Gözetim Sorumlusu',
    denetlenenBirim: 'Denetlenen Birim',
    uyumGorevlisi: 'Uyum Görevlisi',
    platform: 'Pharos Platformu',
    auditModule: 'Pharos Audit',
    riskModule: 'Pharos Risk',
    sanctionModule: 'Pharos Sanction',
    adminModule: 'Pharos Admin',
    controlModule: 'Pharos Control',
    auditModuleDescription: 'Denetim evrenini yönetin; risk esaslı yıllık planı kurun, saha çalışmasını ve çalışma kâğıtlarını yürütün, örneklem alın, bulguları birimlerle uzlaştırın, aksiyonları izleyin ve kurul raporlarını üretin.',
    riskModuleDescription: 'Mevzuat limitlerini ve finansal oranları sürekli izleyin; erken uyarı üretin, senaryo ve stres testi çalıştırın, BDDK cetvellerini hazırlayın.',
    sanctionModuleDescription: 'Yaptırım ve dondurma listelerini otomatik güncelleyin; müşteri portföyünü tarayın, eşleşmeleri karara bağlayın, şüpheli işlem bildirimlerini yönetin.',
    adminModuleDescription: 'Kullanıcı, rol ve yetkileri yönetin; organizasyon yapısını, bildirim ve sistem parametrelerini tanımlayın.',
    controlModuleDescription: 'Kontrol envanterini tutun, birim öz değerlendirmelerini yürütün, kontrol testlerini planlayın ve kontrol etkinliğini raporlayın.',
};
